Test
JenyBuvaka/MyProjectMoove pull request #2
Opened 2024-01-29 12:54 UTC by JenyBuvaka

По идее Это правильно должно быть=))

2024-01-29 18:12 UTC, s-buvaka requested changes
В целом ничего ужасного нет.
Есть много деталей на который стоит обращать внимание.
Комменты отписал выше.
ПРойдись и везде по форматированию.

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/java/com/example/mymovieapp/AdapterMainActivity.kt
> -class AdapterMainActivity(private val clickListener: OnMovieClickListener) :
Пока не очень критично, но именовать такие штуки принято иначе:
- `MainActivityAdapter` - т.е. `Adapter` обозначает тип класса и он обычно пишется в конце (например `PagerAdapter`, `ItemsAdapter` и т.д.)
- А еще лучше называть не `MainActivityAdapter`, а в твоем случае `MovieAdapter`. Таким образом имя говорит о том, что он отображает фильмы, а не привязан к активити. Ведь он же может использоваться не только в одной активити (это норм практика), а привязан к элементу, который он показывает

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/java/com/example/mymovieapp/AdapterMainActivity.kt
> -        listMovie.add(movie)
Очень страннй метод. У тебя тут добавляется всего один элемент `MovieItem`. А адаптер вроде как нужен, чтоб отображать списки. Потому метод должен выглядеть примерно так:

```
fun update(listMovie: List<MovieItem>) {
    this.listMovie = listMovie // только верху listMovie должен быть не `val`, а `var`
    notifyDataSetChanged()
}
```

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/java/com/example/mymovieapp/AdapterMainActivity.kt
> -    val listMovie = ArrayList<MovieItem>()
Тоже правильнее `movieList`, но не критично.

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/java/com/example/mymovieapp/AdapterMainActivity.kt
> -
На скорость работы и качество кода не влияет, но это важно когда ты оформляешь код. Нужно убирать лишние пустые строки. Периодически прожимать автоформатирование

https://www.google.com/search?q=android+studio+auto+format&oq=android+studio+aut&gs_lcrp=EgZjaHJvbWUqBwgBEAAYgAQyBggAEEUYOTIHCAEQABiABDIHCAIQABiABDIHCAMQABiABDIHCAQQABiABDIHCAUQABiABDIHCAYQABiABDIHCAcQABiABDIHCAgQABiABDIHCAkQABiABNIBCDg5MjlqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8

<img width="677" alt="image" src="https://github.com/JenyBuvaka/MyProjectMoove/assets/38229032/f1969f61-8bbb-4d80-8f17-370f57cde670">

Когда ты будешь делать тестовые для собеседований на это будут очень обращать внимание. Чистый и аккуратный код читать приятно, а когда в коде срач, никому не нравится. Потому вырабатывай привычку делать это уже сейчас.

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/java/com/example/mymovieapp/AdapterMainActivity.kt
> -
При этом пустые строки можно оставлять, чтоб резделять логические блоки кода. Например

<img width="946" alt="image" src="https://github.com/JenyBuvaka/MyProjectMoove/assets/38229032/b8ef45b6-2de4-4db7-8539-eb551ad8381e">

на этом скриншоте пустая строка резделяет 2 логических блока кода:
1. Здесь мы получаем переменную и довольно сложной функции
2. Во втором блоке вызываем навигацию

Это проще читается и аккуратнее воспринимается.

А вот пустая строка у тебя в начале ни к селу ни к городу

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/java/com/example/mymovieapp/AdapterMainActivity.kt
> -        @SuppressLint("ResourceType")
Ты вот ты сделал `SuppressLint`. Это линтер, говорит тебе о том, что скорее всего ты что-то делаешь не очень хорошо. Он проверяет твой код на наличие всяких "плохих запахов" в коде.

Иногда с ним можно не согласиться и действительно написать такую штуку, как ты сделал. НО! Важно понимать и делать это осознанно. 

Ты разобрался почему он тут тебе выдает такое сообщение?
Если нет - то ты сделал плохо и иди разбирайся. (вангую, ты сдела так)
Если да и действительно он говорит ерунду - ок.

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/java/com/example/mymovieapp/AdapterMainActivity.kt
> -        val fragment = view.findViewById<ConstraintLayout>(R.id.movie)
`fragment` как бы говорит, что это `Fragment`. А у тебя это совсем не `Fragment`, что вводит в заблуждение.

переименуй в `view` или `parentLayout`

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/java/com/example/mymovieapp/AdapterMainActivity.kt
> -data class MovieItem(
Использовать везде дефолтный значения не всегда нужно.
Это может быть полезно, когда у тебя есть реально какой-то класс, где в большинстве случаев есть какое-то дефолтное значение и в некоторых редких ситуациях может меняться.

Могу ошибаться, но, кажется, у тебя не тот случай. Тем более чтоб все параметры

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/java/com/example/mymovieapp/MainActivity.kt
> -    private lateinit var intent: Intent
У тебя переменная `intent` используется только в одной функции `onCreate`, значит не надо ее делать локальной.
Определи ее внутри `onCreate` и не надо никаких `lateinit`

```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val intent = Intent(this@MainActivity, MovieDetailsActivity::class.java) // вот тут определи и все

        // other code

        adapter = AdapterMainActivity(object : OnMovieClickListener {
            override fun setOnClick(position: Int) {
                startActivity(intent)
            }
        })
    }
```

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/java/com/example/mymovieapp/MainActivity.kt
> -    @SuppressLint("MissingInflatedId")
Опять же, вангую, ты не разобрался и накинул. Плохой тон!

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/java/com/example/mymovieapp/MainActivity.kt
> -    private lateinit var recyclerView: RecyclerView
Вот этот чувак тут должен быть. Он используется и в `onCreate` и в `onConfigurationChanged`

В целом, можно и `lateinit`, но я бы сделал по другому 
```
private val adapter: AdapterMainActivity by lazy { findViewById(R.id.recycler_view) }
```
Так у тебя будет гарантия, что ты не забудешь инициализировать ее до момента первого вызова.
Если не знаешь, что такое `lazy` почитай 

https://bimlibik.github.io/posts/kotlin-lateinit-and-lazy/

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/java/com/example/mymovieapp/MainActivity.kt
> -        val itemList: List<MovieItem> = listOf(
Понимаю, что аппка тестовая и все такое. Но круче будет если для создания такого списка будет использоваться либо отдельный `private` метод либо вообще какой-нибудь класс типа:

```
object MovieStabGenerator {

    fun getMovieList() : List<MovieItem> = listOf(
            MovieItem(
                imgAge = getString(R.string.age_limit_movie_details),
                reviews = getString(R.string.rewiews),
                genre = getString(R.string.genre_movie_details),
                title = getString(R.string.title_movie_AVG),
                filmDuration = getString(R.string.film_duration)
            ),
            MovieItem(),
            MovieItem(),
            MovieItem(),
            MovieItem(),
            MovieItem(),
            MovieItem(),
            MovieItem(),
            MovieItem(),
            MovieItem(),
            MovieItem(
                imgAge = getString(R.string.age_limit_movie_details),
                reviews = getString(R.string.rewiews),
                genre = getString(R.string.genre_movie_details),
                title = getString(R.string.title_movie_AVG),
                filmDuration = getString(R.string.film_duration)
            )
    )
}
```

Так код будет более читаем и аккуратен. Это важно, когда приложение начинает расти

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/java/com/example/mymovieapp/MainActivity.kt
> -        itemList.forEach { adapter.addMovie(it) }
Вот она твоя проблема. Я описал, как выглядеть должен был метод. Чтоб такой ерунды не делать.

В твоем случае мало того, что это некрасиво и неочевидно, так еще если у тебя будет список на 10 элементов, то `notifyDataSetChanged()` внутри адаптера вызовется 10 раз. Будет список на 100 элементов - 100 раз. А этот метод, между прочим, перерисовывает весь список, что может быть заметно (лаги будут) для пользователя (особенно, на старых телефонах)

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/java/com/example/mymovieapp/MainActivity.kt
> -            spanCount = 4
Такие вещи выносятся в константу.
https://www.bestprog.net/ru/2021/07/29/kotlin-variables-and-constants-in-kotlin-ru/

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/java/com/example/mymovieapp/MainActivity.kt
> -        if (config.orientation == ORIENTATION_LANDSCAPE) {
Тут не должно быть `else`? 
Типа если `ORIENTATION_LANDSCAPE` то 4 `spanCount` иначе - 2?

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/java/com/example/mymovieapp/MovieDetailsActivity.kt
> -    @SuppressLint("MissingInflatedId")
Разобраться с `SuppressLint`

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/res/layout-land/activity_main.xml
> -
Лишняя пустая строка.
И так же прожимай автоформатирование (см выше)

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/res/layout-land/activity_main.xml
> -
Тут не нужна пустая строка

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/res/layout-land/activity_main.xml
> -    <ImageView
А вот перед `<ImageView` не помешала бы пустая строка

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/res/layout-land/activity_main.xml
> -
И вообще пройдись по пустым строкам в файле

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/res/layout-land/activity_main.xml
> -        tools:ignore="ContentDescription" />
`tools:ignore` эти штуки аналогичны `Suppress`. Ставить можно, но понимать когда и где. Потому разберись, почему тебе студия их предложила поставить

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/res/layout-land/fragment_movie_details.xml
> -        android:background="#191926">
Цвета принято хранить в ресурсах.

2024-01-29 18:12 UTC, s-buvaka commented on app/src/main/res/layout-land/fragment_movie_details.xml
> -            android:layout_marginTop="7dp"
Маленький совет. Здесь мб и не надо править, но на будущее

В Android принято все размеры делать кратным 4 или хотя бы 2. 

Принцип использования размеров, кратных 4 пикселям в Android, основан на следующих соображениях:

Улучшение производительности: Когда размеры элементов интерфейса кратны 4, это упрощает вычисления для графического процессора. Графические процессоры оптимизированы для работы с числами, которые легко делятся, и кратные 4 значения помогают снизить нагрузку на GPU.

Совместимость с разными экранами: Android устройства имеют широкий спектр разрешений экрана. Использование размеров, кратных 4, помогает обеспечить более согласованный и предсказуемый внешний вид интерфейса на различных устройствах, так как это упрощает масштабирование и адаптацию интерфейса.

Предотвращение искажений: Когда элементы интерфейса имеют размеры, кратные 4, это помогает избежать проблем с искажением или неровными краями, особенно при масштабировании или преобразовании элементов.

Улучшение визуальной эстетики: Это также может помочь в создании более гармоничного и сбалансированного дизайна. Следование сетке с шагом в 4 пикселя помогает дизайнерам и разработчикам легче выравнивать элементы интерфейса относительно друг друга.

Это общие рекомендации, и они не являются строгими правилами. Разработчики и дизайнеры могут выбирать подходящие размеры в зависимости от конкретных требований и целей дизайна.

Даже если дизайнеры рисуют 7 или 9, то стоит им придти и об этом сказать

2024-01-30 19:58 UTC, JenyBuvaka commented on app/src/main/java/com/example/mymovieapp/AdapterMainActivity.kt
> -        listMovie.add(movie)
Странно , в мейн ветке именно так он и выглядит =))) по ходу случайно удалил.

2024-02-01 22:33 UTC, closed without merging